#!/usr/bin/env python
import RPi.GPIO as GPIO
import notifications as ntf


KnockPin = 11 

def setup():
    GPIO.setmode(GPIO.BOARD)       # Numbers GPIOs by physical location
    GPIO.setup(KnockPin, GPIO.IN, pull_up_down=GPIO.PUD_UP)

def swLed(ev=None):
    print("knock")
    ntf.buzz()
    ntf.push()
    print("message sent")

def loop():             
    GPIO.add_event_detect(KnockPin, GPIO.FALLING, callback=swLed, bouncetime=200) 
    while True:
        pass  

def destroy():
    GPIO.cleanup()                     
if __name__ == '__main__':    
    setup()
    try:
        loop()
    except KeyboardInterrupt:  
        destroy()
